# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Placed-Rest Rappi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxCodable'
  pod 'Moya/RxSwift', '13.0.0'
  pod 'Lightbox'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Core'
  pod 'Kingfisher', '~> 5.5'

  # Pods for Placed-Rest Rappi

  target 'Placed-Rest RappiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Placed-Rest RappiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
